set-option -sa terminal-overrides ',xterm*:Tc'
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf


set -g default-terminal "xterm-256color"
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g status-position top
